language: python
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
before_install:
  - python3 --version
  - pip3 install -U pip
  - pip3 install -U pytest
  - pip3 install codecov
install:
  - pip3 install -r requirements.txt # install package + test dependencies
script: 
  - python3 GenBOX.py
  - python3 SpyCAM.py

